### ISSUE TITLE
Unable to run DemoGlobalHistogramTransfer

### ISSUE THREAD

**Issue by Tranvick** [junyanz/interactive-deep-colorization#1]
`Could not open file ./models/global_model/dummy.caffemodel`
I've tried to download it from http://colorization.eecs.berkeley.edu/siggraph/models/dummy.caffemodel like other models in models/fetch_models.sh, but it isn't there.

Also there is a small issue on https://richzhang.github.io/ideepcolor/ page. Link in "Try the network" section leads to non-existent page https://github.com/junyanz/iColor_release

**Comment by richzhang** [comment]
Hi, thanks for catching this! I added dummy to the fetching script.

**Comment by Tranvick** [comment]
No problem. I'm actually still unable to run this notebook due to 

> W0515 03:20:31.042323  3789 _caffe.cpp:142] Net('./models/global_model/global_stats.prototxt', 1, weights='./models/global_model/dummy.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 99:16: Message type "caffe.LayerParameter" has no field named "resize_param".

Maybe I have something wrong with caffe or protobuf installation, but ideepcolor.py and DemoInteractiveColorization.ipynb work great.

**Comment by richzhang** [comment]
Great, thanks for trying our code!

I slightly changed global_stats.prototxt to use pooling instead of resize. Does it work now?

**Comment by Tranvick** [comment]
Almost. It looks like a little inconsistency in filenames. I replaced 

> caffe_files/caffe_traininglayers.py:import rz_fcns_nohdf5 as rz
caffe_files/caffe_datalayers.py:import rz_fcns as rz
caffe_files/color_quantization.py:import rz_fcns as rz

but there is only `./caffe_files/rz_fcns_nohdf5.py
`
I changed all names to rz_fcns and it looks like the problem is fixed. Now I get

> IOError: [Errno 2] No such file or directory: '/home/eecs/rich.zhang/src/projects/cross_domain/save/ab_grid_10/pts_in_hull.npy'

**Comment by Tranvick** [comment]
[Full trace](https://pastebin.com/CrDDK2f7)

**Comment by Antoha-94** [comment]
cant donload this programm.... Can you give please link for me?

**Comment by richzhang** [comment]
Thanks @Tranvick. I changed the import and the pathing to the reference grid files. Let me know if it works now.

**Comment by Antoha-94** [comment]
Have you full version whith ,exe file?

**Comment by blshkv** [comment]
@Antoha-94 эта программа не для винды. Если хочешь, бери исходники и доделывай. Но не мешай тут. Тут другая тема.

**Comment by Tranvick** [comment]
No, it does not work. I still get 

`IOError: [Errno 2] No such file or directory: '/home/eecs/rich.zhang/src/projects/cross_domain/save/ab_grid_10/pts_in_hull.npy'`

[Full trace](https://pastebin.com/0ZFXp9H8)

**Comment by Tranvick** [comment]
I fixed this issue by changing caffe_files/caffe_datalayers.py:42 from 
`self.ENC_DIR = '/home/eecs/rich.zhang/src/projects/cross_domain/save/ab_grid_10`
to
`self.ENC_DIR = 'data/color_bins'`
But it will only work if you run notebook from interactive-deep-colorization/ folder

**Comment by Tranvick** [comment]
I'm not sure but It could be scikit-learn related problem. Which version of scikit-learn do you use? I have 0.18.1

**Comment by richzhang** [comment]
Fixed this by typecasting NN as an int. `https://github.com/junyanz/interactive-deep-colorization/blob/master/caffe_files/color_quantization.py#L19`. An older version of scikit-learn may have been typecasting automatically. Thanks!

**Comment by gaoyangyiqiao** [comment]
I met problems too when running this demo:
`ImportError: No module named caffe_traininglayers`
could you tell what's wrong with it? @Tranvick @richzhang
