### ISSUE TITLE
Incomplete installation instructions 

### ISSUE THREAD

**Issue by ntropia2** [junyanz/interactive-deep-colorization#14]
It's an extremely interesting project, thank you much for sharing it!

Unfortunately, instructions on the installation are not particularly clear and require a significant amount of trial and error, even for people with Python experience.

I personally gave up before having anything working, but I'm sure a step-by-step guide would be definitely much appreciated by many users.

**Comment by jlh36** [comment]
Por favor ayuda, el proyecto es genial, he intentado instalarlos y no puedo, mis conocimientos de Linux son de novato y mis 8 horas de intento fueron un fracaso, necesitamos un manual, gracias

**Comment by junyanz** [comment]
Thank @SleepProgger for providing the installation guidelines. I updated the installation instructions with more details. Let me know if I missed something. For the Caffe installation, there are already a few good documents online. I encourage you to look at [ubuntu-caffe](http://caffe.berkeleyvision.org/install_apt.html), this [note](https://gist.github.com/titipata/f0ef48ad2f0ebc07bcb9) or [ubuntu16.04](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide)
