### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by Boggartfly** [junyanz/interactive-deep-colorization#16]
As I see, the majority of users who actually will prefer to use a GUI are on the Windows platform. Does this code repo work with Windows?
I have an active installation of most of what is mentioned here, so I'm contemplating a test run.
Eager to hear from you guys!

**Comment by richzhang** [comment]
We don't currently have plans for a Windows release. If someone can figure it out, we would be happy to incorporate it into the repo!

**Comment by Java8Caffeine** [comment]
I managed to get ideepcolor.py working on Windows 10 by installing the Windows fork of Caffe in an Anaconda environment. Here's an example of my .bat file that I use in the same directory as ideepcolor.py:

call activate caffe3
python ideepcolor.py --win_size 512 --image_file images/in.jpg --gpu 0
pause

**Comment by UnityUser** [comment]
Java8Caffeine, does it supports CUDA in Windows if you set --gpu 1 with your script?

**Comment by Java8Caffeine** [comment]
It definitely supports CUDA on Windows, but I don't know from experience if --gpu 1 works since I only have 1 gpu to work with. I used --gpu 0 because the indexing starts at 0. I would assume that --gpu 1 would make the program use your 2nd gpu otherwise there would be no point to having the --gpu flag in the first place.

**Comment by UnityUser** [comment]
No, --gpu 0 means DON'T use GPU.
 --gpu 1 means USE gpu ;)

**Comment by junyanz** [comment]
I think --gpu -1 (or --cpu) means DON'T use gpu. 
gpu ids starts at 0.

**Comment by UnityUser** [comment]
Ah, you are right.

**Comment by UnityUser** [comment]
Java8Caffeine, can you describe steps to install it on Win10 plz?
