### ISSUE TITLE
technical requirements

### ISSUE THREAD

**Issue by newcomertoideepcolor** [junyanz/interactive-deep-colorization#19]
What are the technical requirements for running ideepcolor?
I try to run it on Intel i7-4471 CPU 3,5 GHz, 8Gb RAM, invidia geforce gtx 1050 ti 4gb, (CUDA 8.0 with CuDNN 6 or without) but get an error: cudaSuccess (2 vs. 0) out of memory.

**Comment by mosteo** [comment]
I've run it successfully in a 8GB card. I failed previously with a 2GB one.

**Comment by sabrinawallner** [comment]
I believe @SleepProgger provided a way to maybe make this work for you (scroll down to the end of their answer): https://github.com/junyanz/interactive-deep-colorization/issues/10#issuecomment-305660372

**Comment by SleepProgger** [comment]
[Here](https://gist.github.com/SleepProgger/c4a7239c5a7bec16749f7483b388a3e8) is the (dirty) script linked in that issue.
If you are using it for python2 change line 7 to `PYTHON="python"`.
It sacrifices quality and it isn't really the correct approach tho.
I have no clue about caffe, so if someone who does could figure out how to properly reduce the batch size that would be awesome.

**Comment by junyanz** [comment]
I can run the program on a GTX 1080 with 8 GB memory. The program consumes 4.5 GB GPU memory for the default test image `mortar_pestle.jpg`

**Comment by Daniel0034** [comment]
Is ATI Radeon are supports ?

**Comment by junyanz** [comment]
AMD/ ATI Radeon is currently not supported. Caffe actually has an Opencl [version](https://github.com/BVLC/caffe/tree/opencl), and it would be great if someone can port the code to the opencl version.
