### ISSUE TITLE
model.caffemodel is missing

### ISSUE THREAD

**Issue by lucianoocosta** [junyanz/interactive-deep-colorization#21]
Traceback (most recent call last):
  File "ideepcolor.py", line 53, in <module>
    colorModel.prep_net(args.gpu, args.color_prototxt, args.color_caffemodel)
  File "/home/luciano-oc/ideepcolor/data/colorize_image.py", line 234, in prep_net
    self.net = caffe.Net(prototxt_path, caffemodel_path, caffe.TEST)
RuntimeError: Could not open file ./models/reference_model/model.caffemodel

**Comment by lucianoocosta** [comment]
My mistake. Sorry.

**Comment by junyanz** [comment]
Yeah, I guess you need to download the model `bash ./models/fetch_models.sh`
