### ISSUE TITLE
Output colorization doesn't seem to work

### ISSUE THREAD

**Issue by Yourathernot** [junyanz/interactive-deep-colorization#22]
Interactive colorization in the result window doesn't work. 
Output just stays grey. 

I made a change to prototxt files lowering 
`input_param { shape { dim: 1 dim: 4 dim: 128 dim: 128 } } `
and --load_size **128** (default 256) to be able to execute it because I've been running out of GPU memory and getting cudasuccess error. Previously, I ran it in cpu_mode but it was very laggy and output didn't work as well.

- GeForce GT 635M 2GB
- Ubuntu 16.04

**Comment by dbrant** [comment]
Same here... the output image remains gray, regardless of the interactions in the drawing pad (I just ran it with all default parameters). There don't seem to be any errors in the console output.

Ubuntu 16.04, GeForce GTX 1060 6GB

**Comment by dbrant** [comment]
Wait, hang on... I just re-downloaded the reference models (`bash ./models/fetch_models.sh`) after setting everything up, and upon re-running the interactive gui, everything works!  Can you try re-downloading the models and see if that solves it for you, too?

**Comment by Yourathernot** [comment]
I reuploaded models but it still wouldn't colorize them. But I figured it out. First time I forgot to change parameters in global_model as well. It worked after changing them to 128 instead of 256. I believe image quality is decreased but I guess that is as far as one could get without buying better GPU
