### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by UnityUser** [junyanz/interactive-deep-colorization#27]
I try to run:
python ideepcolor.py --gpu 0
But I get the error:
Setting ab cluster centers in layer: pred_ab
Setting upsampling layer kernel: pred_313_us
test_imgs/mortar_pestle.jpg
scale = 2.000000
F0805 19:15:20.179786  3421 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted

I have GTX 660 with 2GB of vram. Is it not enough? What graphic card do I need to run ideepcolor?

**Comment by HenkPoley** [comment]
Apparently 3GB is not enough either: https://github.com/junyanz/interactive-deep-colorization/issues/9

There they mention that running on CPU it takes 4.7GB. Of course a part of that is python all the the support libraries. But it should give sort of ballpark requirements.
