### ISSUE TITLE
Can we get a working Docker image or Dockerfile to aid installation?

### ISSUE THREAD

**Issue by chrisuehlinger** [junyanz/interactive-deep-colorization#29]
I've been trying to install the dependencies for this project about a half dozen times, and still haven't been able to create a working image. If someone who has been able to get this working could write up a Dockerfile (and better yet, build an image to Docker hub) it would certainly make installation much easier.

Short of that, if I could get answers to the following questions, it would really help me out:
- Should I install caffe against the most modern versions of CUDA and CuDNN? Or are there older versions that are preferred?
- I keep getting told (by Ubuntu 16.04) that IPython is deprecated, and that I should install Jupyter. Is that necessary? Will this work with Jupyter? Or should I just find a way to plow through?
- When installing python dependencies (and messing with Caffe's Makefile.config) should I be trying to target Python 2 or 3?
- Is there a preferred way of installing OpenCV? Should it be installed before Caffe? And should I use the version from pip or apt?

Thanks!

**Comment by panuganti** [comment]
@chrisuehlinger I used Bitfusion's AMI image on Amazon EC2 and that works fine for me. You should try.

**Comment by junyanz** [comment]
See this [post](https://github.com/junyanz/interactive-deep-colorization/issues/10) for the installation help. In the post, you can find a docker image provided by @sabrinawallner.
