### ISSUE TITLE
Colorization not working

### ISSUE THREAD

**Issue by vbisbest** [junyanz/interactive-deep-colorization#35]
I am running ideepcolor on OSX with @sabrinawaller docker image.  Everything looks pretty good, but nothing gets colorized.   A screenshot is attached.   Any ideas on what I am missing?  Thank you.
<img width="1415" alt="screen shot 2017-11-28 at 9 58 15 pm" src="https://user-images.githubusercontent.com/3143293/33355851-4bf8a486-d487-11e7-943f-b7d9f19cc5ca.png">

**Comment by vbisbest** [comment]
Found the issue, the models were not downloaded in the docker image.  Once the models were updated it all worked!

**Comment by junyanz** [comment]
Cool. Glad that you can run it on OSX.

**Comment by jx2014** [comment]
Are you running CPU-only mode or does your OSX has CUDA support?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vbisbest** [comment]
@junyanz I have recorded a video on how to get it setup and made the docker image public.  Feel free to share the links and info.

Setup Video: https://youtu.be/IORcb4lQlxQ
Docker Image and Instructions: https://hub.docker.com/r/vbisbest/ideepcolor_osx/

@jx2014 I am runnning in CPU mode and works well.

**Comment by jx2014** [comment]
boy, you got a fast PC.
