### ISSUE TITLE
Change image format (to 512x512?)

### ISSUE THREAD

**Issue by HugoPerrier** [junyanz/interactive-deep-colorization#36]
Hello,

Thanks for the colorization algo, it is great!

I guess the caffe model only accept 256x256 images.
Is there a pre-trained model that takes bigger images?

I have been playing with the "DemoInteractiveColorization" Notebook (I am using Docker and I couldn't get the GUI to work).

I made some cool colorization adding user inputs with output format is 256x256.
I tried to change the size to 512x512 with:
`colorModel = CI.ColorizeImageCaffe(Xd=img_size)`

But it crashes in the forward pass:
`img_out = colorModel.net_forward(input_ab,mask)`

Best

**Comment by junyanz** [comment]
Unfortunately, the current Caffe model only supports 256x256.
