### ISSUE TITLE
Limited color choices and what is the method to colorize surroundings

### ISSUE THREAD

**Issue by gaoyangyiqiao** [junyanz/interactive-deep-colorization#38]
Though it give us some choices, there are limited choices in the palette. 
Does it means that we cannot colorize it to any color? And I'm confused that when colorizing after deciding the (a,b) for a point, how is each pixel around colorized by the network, I mean, does it colorized the around area according to the lightness and segmentation?
Hope that somebody can help.
greetings!

**Comment by junyanz** [comment]
- In addition to the recommended ten colors, you can choose any color from the top-left ab color gamut.
- The software builds on a deep neural network, which automatically propagates the selected color to nearby pixels based on visual cues such as color, texture, and other high-level semantics. See our SIGGRAPH [paper](https://arxiv.org/pdf/1705.02999.pdf) for more details.

**Comment by gaoyangyiqiao** [comment]
@junyanz Thanks a lot!

**Comment by gaoyangyiqiao** [comment]
@junyanz Sorry for troubling again, I'm curious about how the network propagates. Does it use some method? for example , the method Levin used in Colorization Using Optimization in 2004?

**Comment by junyanz** [comment]
We train a deep neural network F to produce RGB images: i.e. RGB_result = F(grayscale_input, user_points). See the [paper](https://arxiv.org/pdf/1705.02999.pdf) Sec 3.1, our [video](https://www.youtube.com/watch?v=FTzcFsz2xqw&feature=youtu.be&t=992), and [slides](https://www.dropbox.com/s/urmifx558nw0ogi/release.pptx?dl=0) for more details.

**Comment by gaoyangyiqiao** [comment]
Thanks again!
