### ISSUE TITLE
unable to start in CPU mode

### ISSUE THREAD

**Issue by blshkv** [junyanz/interactive-deep-colorization#4]
I do not have a nvidia hardware and unable to use GPU.
Caffe does support cpu only, using the ```CPU_ONLY := 1``` flag.
However, ideepcolor is unable to start, the error message is below:
```
python2 ideepcolor.py
[user_study] = False
[dist_caffemodel] = ./models/reference_model/model.caffemodel
[ui_time] = 60
[load_size] = 256
[color_prototxt] = ./models/reference_model/deploy_nodist.prototxt
[color_caffemodel] = ./models/reference_model/model.caffemodel
[dist_prototxt] = ./models/reference_model/deploy_nopred.prototxt
[no_dist] = False
[gpu] = 0
[image_file] = test_imgs/mortar_pestle.jpg
[win_size] = 512
ColorizeImageCaffe instantiated
gpu_id = 0, net_path = ./models/reference_model/deploy_nodist.prototxt, model_path = ./models/reference_model/model.caffemodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0519 12:22:16.921299 11148 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted
```

Could you implement ```--CPU``` flag please?

**Comment by JS1982** [comment]
If you change in _data/colorize_image.py_ under `def prep_net...`
```
caffe.set_device(gpu_id)
caffe.set_mode_gpu()
```

to

```
# caffe.set_device(gpu_id)
# caffe.set_mode_gpu()
caffe.set_mode_cpu()
```

it will work in CPU only mode :)

**Comment by Tranvick** [comment]
@JS1982 
How did you make DemoGlobalHistogramTransfer.ipynb work? 
Have you fixed [these](https://github.com/junyanz/interactive-deep-colorization/issues/1) issues somehow?

**Comment by JS1982** [comment]
No issue at all you have. Installed it following these 2 guidelines on Ubuntu:

OpenCV 3.2.0
http://withr.me/install-opencv-on-ubuntu-16/

Caffe
http://caffe.berkeleyvision.org/installation.html

It's running on OpenBLAS and with CPU only mode

**Comment by richzhang** [comment]
I added a --cpu_mode flag. It is rather slow in cpu mode (~5 seconds for a forward prop), so you'll have to be patient when interacting with the GUI!

**Comment by blshkv** [comment]
Ok, thanks. It works, but it is really slow. It is much slower than I could imanage actually.
It uses 1 cpu only (not threaded?) and it takes 4.30 min just to load the GUI interface and 1.40 min for each and every click (regardless of the operation).

Is anything can be optimised here which could benefit GPU users as well?

**Comment by richzhang** [comment]
I'm not sure, but perhaps you can try to find how to do multi-threading with caffe?

**Comment by blshkv** [comment]
It looks like that I have to use OpenBLAS and no further code change is required. I'll look into it.

Thank you for the great work!

**Comment by mrlzc** [comment]
@blshkv 
I like you use the cpu mode, but I follow this method to run the program directly down, do you have to meet this error?The error message is:

I0526 15:59:48.609108  5621 net.cpp:744] Ignoring source layer loss_log
Setting ab cluster centers in layer: pred_ab
Setting upsampling layer kernel: pred_313_us
test_imgs/mortar_pestle.jpg
scale = 2.000000
Has been killed

**Comment by blshkv** [comment]
sorry, no idea. I suggest to open a separate bug report, provide crash core, strace, system logs or anything else which could be useful to trace the problem.

**Comment by junyanz** [comment]
@mrlzc  Did you compile the Caffe with the python layer support? See this [post](https://chrischoy.github.io/research/caffe-python-layer/)  for more details.

**Comment by leoamr** [comment]
I have the same issue:

I0526 15:59:48.609108 5621 net.cpp:744] Ignoring source layer loss_log
Setting ab cluster centers in layer: pred_ab
Setting upsampling layer kernel: pred_313_us
test_imgs/mortar_pestle.jpg
scale = 2.000000
Has been killed

I re-compiled the Caffe with the python layer support, same error.

**Comment by mrlzc** [comment]
@leoamr I have solved this problem，I use the ubuntu virtual machine, I changed the memory from 4G to 8G, to solve this problem，you can try it...good luck!

**Comment by leoamr** [comment]
@mrlzc increasing the memory solved the problem for me too, thank you very much.

**Comment by captkkk** [comment]
I got these lines after a long length of lines (attached all in separate file):

Setting ab cluster centers in layer: pred_ab
Setting upsampling layer kernel: pred_313_us
b'test_imgs/mortar_pestle.jpg'
Traceback (most recent call last):
  File "ideepcolor.py", line 61, in <module>
    img_file=args.image_file, load_size=args.load_size, win_size=args.win_size)
  File "/home/wongkkk/Documents/Python/colorization-master/interactive-deep-colorization/ui/gui_design.py", line 112, in __init__
    self.drawWidget.init_result(img_file)
  File "/home/wongkkk/Documents/Python/colorization-master/interactive-deep-colorization/ui/gui_draw.py", line 56, in init_result
    self.read_image(image_file.encode('utf-8'))  # read an image
  File "/home/wongkkk/Documents/Python/colorization-master/interactive-deep-colorization/ui/gui_draw.py", line 81, in read_image
    im_bgr = cv2.imread(image_file)
TypeError: bad argument type for built-in operation

[python3 ideepcolor.py error.txt](https://github.com/junyanz/interactive-deep-colorization/files/2132430/python3.ideepcolor.py.error.txt)

**Comment by blshkv** [comment]
Guys, your problem is NOT related to this bug. Please stop flooding it and open a new one.

**Comment by junyanz** [comment]
@captkkk You probably should start a separate Github issue next time. For your question, you can remove .encode('utf-8'). See this [post](https://github.com/junyanz/interactive-deep-colorization/issues/40) for more details.

**Comment by captkkk** [comment]
OK, sorry for the trouble caused.
