### ISSUE TITLE
UnicodeDecodeError Using ideepcolor in CPU mode

### ISSUE THREAD

**Issue by FoxTrotte** [junyanz/interactive-deep-colorization#42]
Hi !

My issue is that whan i type the following command: 
`python ideepcolor.py --cpu_mode --image_file ~/Téléchargements/bw.jpg`
I get the following error:
`UnicodeDecodeError: "ascii" codec can't decode byte 0xc3 in position 14: ordinal not in range(128)`
I can't try GPU mode since I only have an Intel integrated on my laptop.
I'm on Ubuntu 16.04, caffe imports well.
Note: Téléchargements is french for downloads.

Thanks a lot for reading, I hope there is a solution to this problem. Thanks.

**Comment by junyanz** [comment]
It may be due to the language. Could you rename Téléchargements to an English name?

**Comment by FoxTrotte** [comment]
Oh god I feel stupid how did I not try this ^^

Thanks so much it launches now !!!

**Comment by junyanz** [comment]
Glad that you fixed it.
