### ISSUE TITLE
Size of palette 

### ISSUE THREAD

**Issue by Arroosh** [junyanz/interactive-deep-colorization#45]
Hello!
Can you please tell me that can we increase the size of palette or suggested colors using this code? If so then which command lines will be require to make changes in the code?

Thanks in advance

Regards
Aroosh Fatima

**Comment by junyanz** [comment]
It's currently hard-coded in the code. You can change the size by modifying this [line](https://github.com/junyanz/interactive-deep-colorization/blob/master/ui/gui_palette.py#L9).

**Comment by Arroosh** [comment]
Thanks for your response.
In case of user edit, I want to add R,G,B  color values of my own choice on specific position. Is this possible??
If so, Please highlight those lines (R, G, B values as well as x,y position) as well where i need to make changes.

Thanks in advance

Regards
Aroosh Fatima

**Comment by junyanz** [comment]
It's possible. But you need to hack the code. You can either modify the jupyter [notebook](https://github.com/junyanz/interactive-deep-colorization#2a-barebones-interactive-colorization-demo). You need to set the input_ab and mask manually in Line 7. For the UI code, you need to modify this [line](https://github.com/junyanz/interactive-deep-colorization/blob/master/ui/gui_draw.py#L277).

**Comment by kz81** [comment]
Palette can be adjusted easily, but how do I change the brush size?
I can do a palette with tiny colors, but the brush (tooltip) will remain standard size.
A fine tooltip should improve results significantly for example in group pictures with rather small faces. Even better would be if there were several tooltip sizes to choose from within the program while running.

**Comment by kz81** [comment]
Genius! :) Thank you!
