### ISSUE TITLE
Keep the original width & height of image

### ISSUE THREAD

**Issue by sujameslin** [junyanz/interactive-deep-colorization#46]
Is there anyway to have same width & height with original for the output picture?
It always output picture with fixed width 1200px no matter what size of image that I loaded.

Thanks

**Comment by junyanz** [comment]
It should be fixed by this [commit](https://github.com/junyanz/interactive-deep-colorization/commit/b9fb77fba53229bff8dbcb2a0c7fa42a5afdc8dc).

**Comment by sujameslin** [comment]
No, I was running via docker. Used this image.
https://hub.docker.com/r/vbisbest/ideepcolor_osx/

**Comment by sujameslin** [comment]
@junyanz Yes. it worked. The docker image contains a bit old code which doesn't include that commit. 
I did git pull and it works. 
Thanks

**Comment by rtrudes** [comment]
> @junyanz Yes. it worked. The docker image contains a bit old code which doesn't include that commit.
> I did git pull and it works.
> Thanks

Hello, I'm facing the same issue. How did you do the git pull? Can you help me? Thanks
