### ISSUE TITLE
Does color input keep the same after colorization?

### ISSUE THREAD

**Issue by hailehong** [junyanz/interactive-deep-colorization#48]
Hi,
I have not installed the code successfully.
Could you tell me, is the color at input point will not be changed after colorization or it will be changed little bit? I would like the input color  is not be changed after colorization.

Thank you.

**Comment by junyanz** [comment]
Sometimes It may change slightly (e.g., < 5 out of [0, 255]), but in most cases, you cannot notice the difference.

**Comment by hailehong** [comment]
Thanks for your information.
