### ISSUE TITLE
Windows Installation - Models

### ISSUE THREAD

**Issue by kz81** [junyanz/interactive-deep-colorization#51]
I am new to most parts of this project (Anaconda/Python, Caffe, Visual Studio etc.) so please understand my question may be very basic or even obvious.

What I have done
After a longer phase of trial & error I have managed to 
- build Caffe under Windows
- Install Anaconda/Python
- Install missing packages and update/downgrade any parts that will lead to error messages (scikit-image, scikit-learn, opencv, Qt4, QDarkStyle etc.)
- Run ideepcolor.py and find workarounds for all error messages, like: 
  - no module named skimage
  - dll load failed (PIL)
  - module object has no attribute bool_ 
  - dll load failed (from . import _imaging as core / image.py)
  - The specified module could not be found (DLL missing)
  and some others

Status/Problem
- ideepcolor.py will not do anything:
- I can run ideepcolor.py without any error messages and without crashing
- but the terminal window will not change except for the blinking cursor, and the memory usage will not change (memory usage around 45,5 to 50,8 MB, depending on command; processor usage moving around 16%; HDD usage is ZERO).

Question
- Does that mean the program has hung up? Or do I just have to wait VERY long time until processing will move on (I have already waited for several hours without any change)?
- As I do not get error messages any more, what can I possibly do to find the source of error?

Any help would be highly appreciated!
Kind regards,

K
![grafik](https://user-images.githubusercontent.com/34928140/43380601-b5a2214c-940c-11e8-8ff3-e9f1aaee2b3f.png)
![grafik](https://user-images.githubusercontent.com/34928140/43380633-c37e1906-940c-11e8-917e-d218a9ef62d5.png)

**Comment by kz81** [comment]
After rebuilding Caffe without errors, ideepcolor.py starts to run, but stops with error: 
runtime error: could not open ...model.caffemodel
Any hints on this problem?

![grafik](https://user-images.githubusercontent.com/34928140/43387135-9dfed1c0-9420-11e8-86cb-68a76c75df9f.png)

**Comment by kz81** [comment]
Finally I understood that "fetch_models.sh" is not the model, but the script for getting the model data.
Under Windows, where there is no bash command available, I suppose you can just open the file in editor, check the path and copy the files manually to their destinations.
SOLVED!

**Comment by leo1243** [comment]
Hello can you do tutorial somewhere please.
