### ISSUE TITLE
About shortcut connection

### ISSUE THREAD

**Issue by yellowisher** [junyanz/interactive-deep-colorization#55]
It seems that previous tensors are added with convolution operation in shortcut connection.
But in U-Net(which you referenced), shortcut connection contains no convolution but only concatenation.
Is there any reason or source for using <code>conv+add</code> over <code>concat</code> or just <code>add</code>? 

<pre><code># Conv7    
model8up = [nn.ConvTranspose2d(512, 256, kernel_size=4, stride=2, padding=1, bias=use_bias)]
model3short8 = [nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1, bias=use_bias), ]
.
.
.
conv8_up = self.model8up(conv7_3) + self.model3short8(conv3_3)
</code></pre>

**Comment by richzhang** [comment]
They are somewhat equivalent: conv_{ab}(concat(a,b)) is actually equivalent of conv_{a}(a)+conv_{b}(b). The weights of conv_{ab} are the weights of conv_{a} and conv_{b} concatenated.

**Comment by yellowisher** [comment]
Oh I just figured it out. Thanks for the answer.
