### ISSUE TITLE
The program is very heavy

### ISSUE THREAD

**Issue by fahriy** [junyanz/interactive-deep-colorization#59]
Hello there;
I'm running the program reference model "coffee cup" is installed waiting for 3-4 minutes.
I wait 3-4 minutes again when I upload black and white photos. I look forward to the photo again when I choose the nir point. This way, it takes a long time to color the picture. What could be the cause of this slowness? What are the required system features?

My Computer features
Operating system: Ubuntu 18.04.1 LTS
CPU: Intel (R) Core (TM) i7-2600 CPU @ 3.40GHz, 3392 MHz
Memory (RAM): 6 GB
GPU: GeForce GTX 560 2048 MB

**Comment by junyanz** [comment]
Unfortunately, the program requires a more recent GPU (e.g., GTX 1080) with CUDNN for real-time performance.
