### ISSUE TITLE
missed required dependencies

### ISSUE THREAD

**Issue by blshkv** [junyanz/interactive-deep-colorization#6]
I had to install the following two dependencies before I was able to start the software:
```
sci-libs/scikits_learn
dev-python/jsonschema
```

The list might not be comprehensive since I have a fully loaded system. Please double check "import" lines.

**Comment by blshkv** [comment]
You closed the bug without any explanation. This is good, but i will not report any other bugs. Just to let you know

**Comment by junyanz** [comment]
Thanks for reporting the bug. `scikits_learn` has been included in the required dependences. I am not sure if `jsonschema` is necessary.

**Comment by blshkv** [comment]
ok, noted
