### ISSUE TITLE
Scale up the input size

### ISSUE THREAD

**Issue by i-radwan** [junyanz/interactive-deep-colorization#62]
Hi there,
Thanks for your great effort. I've  a question related to the input shape, can we scale it up to colorize large input images (e.g. 1024 * 1024)? I guess the model won't fit in a 6 GB GPU, but can we eliminate some layers and still get good results (I can provide more hints to help the model colorize the large images)?

**Comment by richzhang** [comment]
A hack would be to process it in a sliding window fashion (colorize 256x256 blocks separately). This may give some discontinuities, however. You can also try to process overlapping windows. For example, first colorize the top-left `img[0:256,0:256]`. Then colorize `img[192:448,0:256]`, by first seeding the overlapping region `img[192:256,0:256]` with some randomly selected colored points from the first colorization.
