### ISSUE TITLE
Add Support for RGB/HEX Codes in UI

### ISSUE THREAD

**Issue by Limeysoda1** [junyanz/interactive-deep-colorization#73]
I am on Windows, and the program works perfectly, except choosing a colour is extremely difficult. The Colour selector is extremely slow even in gpu mode. I would love a box to put in a RGB or a HEX Code as to make choosing a colour much easier, especially a known colour.

**Comment by junyanz** [comment]
Maybe you can use [QtColorDialog](https://doc.qt.io/qt-5/qcolordialog.html). Unfortunately, we don't have capacity to add a new feature. For a more professional UI, please refer to the [ColorziePhoto](http://video.tv.adobe.com/v/28291) in Photoshop Element.

**Comment by Limeysoda1** [comment]
Thank you, I will try Photoshop Element
