### ISSUE TITLE
SystemError: <Boost.Python.function object at 0x17369c0> returned NULL without setting an error

### ISSUE THREAD

**Issue by inigo-irigaray** [junyanz/interactive-deep-colorization#78]
![Screenshot 2020-09-04 at 13 12 00](https://user-images.githubusercontent.com/52103993/92233642-f167fc00-eeb0-11ea-8565-6f99ad04e6a1.png)

I get this error when running the Global Histogram Demo notebook on my EC2 instance (python 3.6.3, opencv-python (4.4.0.42). It doesn't seem to find one of the traininglayers of the model. Or it might be something else, I'm new to caffe so I don't understand it quite well yet.

Thanks!

**Comment by crameth** [comment]
Hi, did you manage to fix this somehow? I'm encountering the same issue.
