### ISSUE TITLE
Missing dependency pts_on_hull.py

### ISSUE THREAD

**Issue by JS1982** [junyanz/interactive-deep-colorization#8]
There is still a link to a personal file `pts_on_hull.py` in /home/eecs/rich.zhang/src/projects/cross_domain/save/ab_grid_10

Can you please integrate this necessary file in the project, so when we pull it from git it will work without pulling this file separate

**Comment by Tranvick** [comment]
It looks like it's in data/color_bins/pts_in_hull.npy

**Comment by JS1982** [comment]
If that's the case, please adjust the Python code so it is not looking at the personal folder but at `data/color_bins/`

**Comment by richzhang** [comment]
Updated!

**Comment by richzhang** [comment]
Changed the files to reference local directories. Thanks for the catch!
