### ISSUE TITLE
error:  "name 'unicode' is not defined"

### ISSUE THREAD

**Issue by semel1** [junyanz/interactive-deep-colorization#85]
Finally managed to launch GUI (Windows 10) after replacement in the "gui_draw.py":
      self.read_image(image_file.encode('utf-8'))  # read an image
to
      self.read_image(image_file)  # read an image
Default image (mortar_pestle.jpg) works fine.
However attempt to load image using GUI "Load" button throws an error:

Traceback (most recent call last):
  File "F:\ideepcolor\ui\gui_design.py", line 151, in load
    self.drawWidget.load_image()
  File "F:\ideepcolor\ui\gui_draw.py", line 220, in load_image
    img_path = unicode(QFileDialog.getOpenFileName(self, 'load an input image'))
NameError: name 'unicode' is not defined

**Comment by Blastd** [comment]
change 'unicode' to str
