### ISSUE TITLE
out of VRAM

### ISSUE THREAD

**Issue by clickcell** [junyanz/interactive-deep-colorization#9]
I get this error:

`test_imgs/mortar_pestle.jpg
scale = 2.000000
F0520 22:52:34.222404  2410 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)
`

Trying to run the full GUI demo on a GeForce 970M with 3GB VRAM. Is that not enough? How can I change a configuration to make it use less?

Where do I find the stack trace?

**Comment by ilkeryasinaksoy** [comment]
I have similiar problem. I can't find batch_size. Please help me.

**Comment by clickcell** [comment]
It worked for me in CPU mode, RAM usage was about 4.7GB, so I think

**Comment by ilkeryasinaksoy** [comment]
How did you work in CPU mode?

**Comment by clickcell** [comment]
I followed the instructions in the comment from JS1982 https://github.com/junyanz/interactive-deep-colorization/issues/4#issuecomment-302880879

**Comment by ilkeryasinaksoy** [comment]
Thanks! I will try...

**Comment by SleepProgger** [comment]
It worked for me when i reduced `Xd` / the load_size` parameter.
I am using 128 for ideepcolor and 192 for the coloring by reference.
You need to update the input layer in all prototxt files to match that value.
There is probably a nicer way (reduce the batch size), but i am new to caffe, so no clue about that.

**Comment by whizzzkid** [comment]
CPU mode seems to work, run it like `python ideepcolor.py --gpu -1`

-1 == cpu mode

**Comment by ilkeryasinaksoy** [comment]
I tried it. But the same problem continues.

**Comment by Boggartfly** [comment]
@clickcell My Titan X should work right?, it has 12GB of VRAM.

**Comment by clickcell** [comment]
I reckon so. Let me know.

**Comment by junyanz** [comment]
@ilkeryasinaksoy, could you report the full trace?
