### ISSUE TITLE
Model URL no longer working

### ISSUE THREAD

**Issue by dev0987** [junyanz/interactive-deep-colorization#94]
The Berkeley links with the pre-trained models are no longer accessible. Is there another archive with them ?
 
Not found:
https://colorization.eecs.berkeley.edu/siggraph/models/pytorch.pth

**Comment by Dakes** [comment]
I have uploaded them here: [https://drive.google.com/file/d/1j31_ZOFXrKrTbCpa_2FAwFmaQblO08RL/view?usp=share_link]()

**Comment by Dakes** [comment]
I just checked the link. It does work, but just with HTTP: [http://colorization.eecs.berkeley.edu/siggraph/models/pytorch.pth]()

**Comment by dev0987** [comment]
Thanks for the link. Turns out Firefox https only mode was the culprit, manually adding the full url exception fixes the issue.
